### PR TITLE
[DPB]: Fix stale queue counter maps in COUNTERS_DB after port breakout

### LINKED ISSUE #3983: [DPB]: Stale queue counter mappings in COUNTERS_DB post port breakout
**Description:**
After dynamic port breakout of a port, `show queue counters <Port>` doesn't work as queue counter map in the COUNTERS_DB is not updated.

**How to reproduce:**
Perform breakout of a port and check queue counters after breakout:

```bash
# sudo config interface breakout Ethernet448 "1x800G[400G,200G]" -y -f

Running Breakout Mode : 1x800G[400G,200G]
Target Breakout Mode : 1x800G[400G,200G]
[WARNING] No action will be taken as current and desired Breakout Mode are same.
root@sonic:/home/admin# sudo config interface breakout Ethernet448 "8x100G[50G]" -y -f

Running Breakout Mode : 1x800G[400G,200G]
Target Breakout Mode : 8x100G[50G]

Ports to be deleted :
 {
    "Ethernet448": "800000"
}
Ports to be added :
 {
    "Ethernet448": "100000",
    "Ethernet449": "100000",
    "Ethernet450": "100000",
    "Ethernet451": "100000",
    "Ethernet452": "100000",
    "Ethernet453": "100000",
    "Ethernet454": "100000",
    "Ethernet455": "100000"
}
Breakout process got successfully completed.
Please note loaded setting will be lost after system reboot. To preserve setting, run `config save`.
```

**Issue**
```bash
show queue counters Ethernet0
Traceback (most recent call last):
File "/usr/local/bin/queuestat", line 455, in <module>
main()
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 764, in {}call{}
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/bin/queuestat", line 450, in main
queuestat_wrapper.run(save_fresh_stats, port_to_show_stats, json_opt, non_zero)
File "/usr/local/lib/python3.11/dist-packages/utilities_common/multi_asic.py", line 156, in wrapped_run_on_all_asics
func(self, *args, **kwargs)
File "/usr/local/bin/queuestat", line 117, in run
queuestat = Queuestat(self.multi_asic.current_namespace, self.db, self.voq)
```

### PR DESCRIPTION
**Pull request by rminnikanti**
Fixes #3983 

**What I did**
Added cleanup of COUNTERS_*_NAME_MAP entries for a port during its deinit phase, and regenerated the NAME_MAP tables with fresh OIDs during port init when queue flex counters are already enabled.

**Why I did it**
After dynamic port breakout of a port, queue name map tables in the COUNTERS_DB table are not regenerated leaving stale entries resulting in CLI crash

**How I verified it**
```bash
# show queue counters Ethernet0
For namespace :
     Port    TxQ    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes
---------  -----  --------------  ---------------  -----------  ------------
Ethernet0    UC0               0                0            0             0
Ethernet0    UC1               0                0            0             0
Ethernet0    UC2               0                0            0             0
Ethernet0    UC3               0                0            0             0
Ethernet0    UC4               0                0            0             0
Ethernet0    UC5               0                0            0             0
Ethernet0    UC6               0                0            0             0
Ethernet0    UC7               0                0            0             0

root@sonic:~# redis-dump -d 2 -k "COUNTERS_PORT_NAME_MAP*" | jq | grep Ethernet448
      "Ethernet448": "oid:0x100000000085c",
root@sonic:~#  redis-dump -d 2 -k "COUNTERS_QUEUE_PORT_MAP*" | jq | grep 0x100000000085c
      "oid:0x15000000000860": "oid:0x100000000085c",
      "oid:0x15000000000861": "oid:0x100000000085c",
      "oid:0x15000000000862": "oid:0x100000000085c",
      "oid:0x15000000000863": "oid:0x100000000085c",
      "oid:0x15000000000864": "oid:0x100000000085c",
      "oid:0x1500000000085d": "oid:0x100000000085c",
      "oid:0x1500000000085f": "oid:0x100000000085c",
      "oid:0x1500000000085e": "oid:0x100000000085c",
root@sonic:~# redis-dump -d 2 -k "COUNTERS_QUEUE_NAME_MAP*" | jq | grep -E "0x15000000000860|0x15000000000861|0x15000000000862|0x15000000000863|0x15000000000864|0x1500000000085d|0x1500000000085f|0x1500000000085e"
      "Ethernet448:6": "oid:0x15000000000863",
      "Ethernet448:2": "oid:0x1500000000085f",
      "Ethernet448:4": "oid:0x15000000000861",
      "Ethernet448:7": "oid:0x15000000000864",
      "Ethernet448:3": "oid:0x15000000000860",
      "Ethernet448:0": "oid:0x1500000000085d",
      "Ethernet448:5": "oid:0x15000000000862",
      "Ethernet448:1": "oid:0x1500000000085e",
root@sonic:~# redis-dump -d 2 -k "COUNTERS_QUEUE_INDEX_MAP*" | jq | grep -E "0x15000000000860|0x15000000000861|0x15000000000862|0x15000000000863|0x15000000000864|0x1500000000085d|0x1500000000085f|0x1500000000085e"
      "oid:0x15000000000860": "3",
      "oid:0x15000000000861": "4",
      "oid:0x15000000000862": "5",
      "oid:0x15000000000863": "6",
      "oid:0x15000000000864": "7",
      "oid:0x1500000000085d": "0",
      "oid:0x1500000000085f": "2",
      "oid:0x1500000000085e": "1",
root@sonic:~#  redis-dump -d 2 -k "COUNTERS_QUEUE_TYPE_MAP*" | jq | grep -E "0x15000000000860|0x15000000000861|0x15000000000862|0x15000000000863|0x15000000000864|0x1500000000085d|0x1500000000085f|0x1500000000085e"
      "oid:0x15000000000860": "SAI_QUEUE_TYPE_UNICAST",
      "oid:0x15000000000861": "SAI_QUEUE_TYPE_UNICAST",
      "oid:0x15000000000862": "SAI_QUEUE_TYPE_UNICAST",
      "oid:0x15000000000863": "SAI_QUEUE_TYPE_UNICAST",
      "oid:0x15000000000864": "SAI_QUEUE_TYPE_UNICAST",
      "oid:0x1500000000085d": "SAI_QUEUE_TYPE_UNICAST",
      "oid:0x1500000000085f": "SAI_QUEUE_TYPE_UNICAST",
      "oid:0x1500000000085e": "SAI_QUEUE_TYPE_UNICAST",
```

**Details if related**

### CODE REVIEW

File: orchagent/high_frequency_telemetry/counternameupdater.cpp [hunk 1]
```diff
@@ -40,18 +40,15 @@ void CounterNameMapUpdater::setCounterNameMap(const std::vector<swss::FieldValue
 {
     SWSS_LOG_ENTER();
 
-    if (gHFTOrch)
```
Comment (rminnikanti) [inline orchagent/high_frequency_telemetry/counternameupdater.cpp:43]: @Pterosaur can you please review?

**Review by Pterosaur — APPROVED** [review]
@kperumalbfn Could you please help to review this PR?
If we merge this PR, I will close my PR: https://github.com/sonic-net/sonic-swss/pull/3967 that is duplicated.

File: orchagent/portsorch.cpp [hunk 2]
```diff
@@ -4015,6 +4015,40 @@ void PortsOrch::registerPort(Port &p)
         wred_port_stat_manager.setCounterIdList(p.m_port_id, CounterType::PORT, wred_port_stats);
     }
 
+    // If queue-related flex counters are already enabled, generate queue maps
+    // for the newly added port so that usecases like dynamic port breakout works.
+    bool queueFcEnabled = flex_counters_orch->getQueueCountersState() ||
+                            flex_counters_orch->getQueueWatermarkCountersState() ||
+                            flex_counters_orch->getWredQueueCountersState();
+    if (queueFcEnabled && !p.m_queue_ids.empty())
```
Comment (kperumalbfn) [inline orchagent/portsorch.cpp:4038]: @rminnikanti could you please check the DPB sonic-mgmt tests? If this is not covered, could you please add them?

**Review by kperumalbfn — COMMENTED** [review]
@Pterosaur could you close the PR - https://github.com/sonic-net/sonic-swss/pull/3967

File: orchagent/portsorch.cpp (hunk 2 above)
Comment (rminnikanti) [reply orchagent/portsorch.cpp:4038]: @kperumalbfn I don't see DPB test component in PTF. As far as I understand, DPB testing in sonic-mgmt can be performed on ports that are not part of the topology.

The mock_tests included in this PR verifies the regeneration of the NAME_MAP's. I’ve also validated this behavior on a device and shared the redis-dump output in the PR description for reference.

**Review by kperumalbfn — DISMISSED** [review]

**Comment by sdszhang** [comment]
@rminnikanti  can you create a cherry-pick PR to msft-202412

**Comment by rminnikanti** [comment]
> @rminnikanti can you create a cherry-pick PR to msft-202412

@sdszhang created PR - https://github.com/Azure/sonic-swss.msft/pull/170

**Comment by ZhaohuiS** [comment]
@rminnikanti could you pls help fix the UT failures in PR test?



```
Testsuite summary for sonic-swss 1.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See orchagent/p4orch/tests/test-suite.log
============================================================================
make[5]: *** [Makefile:1884: test-suite.log] Error 1
make[5]: Leaving directory '/__w/1/s/orchagent/p4orch/tests'
make[4]: *** [Makefile:1992: check-TESTS] Error 2
make[4]: Leaving directory '/__w/1/s/orchagent/p4orch/tests'
make[3]: *** [Makefile:2064: check-am] Error 2
make[3]: Leaving directory '/__w/1/s/orchagent/p4orch/tests'
make[2]: *** [Makefile:2756: check-recursive] Error 1
make[2]: Leaving directory '/__w/1/s/orchagent'
make[1]: *** [Makefile:420: check-recursive] Error 1
make[1]: Leaving directory '/__w/1/s'
dh_auto_test: error: make -j4 check "TESTSUITEFLAGS=-j4 --verbose" VERBOSE=1 returned exit code 2
make: *** [debian/rules:22: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2


```

**Comment by r12f** [comment]
hi @rminnikanti , do you mind to help look into this build issue? I will postpone the 202412 branch merge once the master is merged.

**Comment by rminnikanti** [comment]
@r12f @ZhaohuiS Fixed. PR checks passed.

@r12f I have propagated fix to https://github.com/Azure/sonic-swss.msft/pull/170

**Comment by r12f** [comment]
Hi @rminnikanti , we are hitting test failure on 202412 due to the PR being incorrectly ported, do you mind to help us look into it?

@kperumalbfn for viz.

**Comment by rminnikanti** [comment]
> Hi @rminnikanti , we are hitting test failure on 202412 due to the PR being incorrectly ported, do you mind to help us look into it?
> 
> @kperumalbfn for viz.

@r12f I identified the fix. Its not exactly because of the cherry-picked PR but because of a missing mock_table function in 202412. I will fix it soon.

**Comment by r12f** [comment]
Thanks a lot Ravi!

**Comment by rminnikanti** [comment]
> Thanks a lot Ravi!

Created https://github.com/Azure/sonic-swss.msft/pull/175

**Comment by govi-nokia** [comment]
@prsunny Could this fix be taken to 202511 please? Please add the appropriate labels for the same.

@Pavan-Nokia viz
@balanokia viz
@dgodwin-nokia viz

**Comment by dakotac-arista** [comment]
Hi @prsunny, can the fix be backported to msft-202503 as well? PR: https://github.com/Azure/sonic-swss.msft/pull/196
