### PR TITLE
[dualtor] Fix neighbor miss when mux is not ready

### LINKED ISSUE #2675: standalone tunnel route is missing after config reload
## issue description
As the title, after config reload, the standalone tunnel routes could not be restored.

## how to reproduce
1. config first 4 ports admin down
```
# show int s | head -n 10
     Interface            Lanes    Speed    MTU    FEC         Alias            Vlan    Oper    Admin             Type    Asym PFC
--------------  ---------------  -------  -----  -----  ------------  --------------  ------  -------  ---------------  ----------
     Ethernet0          1,2,3,4     100G   9100     rs   Ethernet1/1          routed    down     down  QSFP28 or later         off
     Ethernet4          5,6,7,8     100G   9100     rs   Ethernet2/1           trunk    down     down  QSFP28 or later         off
     Ethernet8       9,10,11,12     100G   9100     rs   Ethernet3/1           trunk    down     down  QSFP28 or later         off
    Ethernet12      13,14,15,16     100G   9100     rs   Ethernet4/1           trunk    down     down  QSFP28 or later         off
    Ethernet16      21,22,23,24     100G   9100     rs   Ethernet5/1           trunk    down     down  QSFP28 or later         off
    Ethernet20      17,18,19,20     100G   9100     rs   Ethernet6/1           trunk      up       up  QSFP28 or later         off
    Ethernet24      25,26,27,28     100G   9100     rs   Ethernet7/1           trunk      up       up  QSFP28 or later         off
    Ethernet28      29,30,31,32     100G   9100     rs   Ethernet8/1           trunk      up       up  QSFP28 or later         off
# show mux s
PORT        STATUS    SERVER_STATUS    HEALTH     HWSTATUS      LAST_SWITCHOVER_TIME
----------  --------  ---------------  ---------  ------------  ---------------------------
Ethernet4   active    unknown          unhealthy  inconsistent
Ethernet8   active    unknown          unhealthy  inconsistent
Ethernet12  active    unknown          unhealthy  inconsistent
Ethernet16  active    unknown          unhealthy  inconsistent
```
2. confirm all the SoC IPs' neighbors for those ports are `FAILED`, and tunnel routes are installed
```
# ip neighbor | grep FAILED
192.168.0.3 dev Vlan1000  FAILED
192.168.0.7 dev Vlan1000  FAILED
192.168.0.5 dev Vlan1000  FAILED
192.168.0.9 dev Vlan1000  FAILED
fe80::9a03:9bff:fe03:2280 dev Vlan1000  FAILED
# show mux tun
PORT        DEST_TYPE    DEST_ADDRESS     kernel    asic
----------  -----------  ---------------  --------  ------
Ethernet4   soc_ipv4     192.168.0.3/32   -         added
Ethernet8   soc_ipv4     192.168.0.5/32   -         added
Ethernet12  soc_ipv4     192.168.0.7/32   -         added
Ethernet16  soc_ipv4     192.168.0.9/32   -         added
```
3. config save && config reload
4. check the neighbor and tunnel route
```
# ip neighbor | grep FAILED
192.168.0.3 dev Vlan1000  FAILED
192.168.0.7 dev Vlan1000  FAILED
192.168.0.5 dev Vlan1000  FAILED
192.168.0.9 dev Vlan1000  FAILED
fe80::50bc:26ff:febb:8711 dev Vlan1000  FAILED
fe80::c0b8:b1ff:fefa:4012 dev Vlan1000  FAILED
fe80::3045:55ff:fe2e:4714 dev Vlan1000  FAILED
fe80::9407:dff:fed5:5516 dev Vlan1000  FAILED
fe80::9a03:9bff:fe03:2280 dev Vlan1000  FAILED
fe80::3825:55ff:fe30:a117 dev Vlan1000  FAILED
fe80::c01b:e7ff:fe50:2515 dev Vlan1000  FAILED
fe80::94f4:44ff:fe05:c818 dev Vlan1000  FAILED
fe80::f2:5ff:fe14:8f13 dev Vlan1000  FAILED
# show mux tun
PORT        DEST_TYPE    DEST_ADDRESS     kernel    asic
----------  -----------  ---------------  --------  ------
Ethernet20  soc_ipv4     192.168.0.11/32  -         added
Ethernet24  soc_ipv4     192.168.0.13/32  -         added
Ethernet28  soc_ipv4     192.168.0.15/32  -         added
Ethernet32  soc_ipv4     192.168.0.17/32  -         added
Ethernet36  soc_ipv4     192.168.0.19/32  -         added
Ethernet40  soc_ipv4     192.168.0.21/32  -         added
Ethernet44  soc_ipv4     192.168.0.23/32  -         added
Ethernet48  soc_ipv4     192.168.0.25/32  -         added
```

* the tunnel routes for `192.168.0.3`, `192.168.0.5`, `192.168.0.7`, `192.168.0.9` are not installed as they are `FAILED` neighbor entries.

## syslog
```
65559:Feb 22 14:53:40.332368  INFO swss#orchagent: :- initHostTxReadyState: initalize hostTxReady Ethernet4 with status
65795:Feb 22 14:53:40.436286  NOTICE swss#orchagent: :- handleMuxCfg: Ethernet4: 192.168.0.3 was added to ignored neighbor list
65796:Feb 22 14:53:40.436286  INFO swss#orchagent: :- handleMuxCfg: Mux Peer switch addr not yet configured, port 'Ethernet4'
65831:Feb 22 14:53:40.437406  NOTICE swss#orchagent: :- handleMuxCfg: Ethernet4: 192.168.0.3 was added to ignored neighbor list
65832:Feb 22 14:53:40.437406  INFO swss#orchagent: :- handleMuxCfg: Mux Peer switch addr not yet configured, port 'Ethernet4'
65869:Feb 22 14:53:40.438186  NOTICE swss#orchagent: :- handleMuxCfg: Ethernet4: 192.168.0.3 was added to ignored neighbor list
65870:Feb 22 14:53:40.438233  INFO swss#orchagent: :- handleMuxCfg: Mux Peer switch addr not yet configured, port 'Ethernet4'
65901:Feb 22 14:53:40.441086  WARNING swss#orchagent: :- addOperation: Mux entry for port 'Ethernet4' doesn't exist
65932:Feb 22 14:53:40.442080  NOTICE swss#orchagent: :- handleMuxCfg: Ethernet4: 192.168.0.3 was added to ignored neighbor list
65933:Feb 22 14:53:40.442080  INFO swss#orchagent: :- handleMuxCfg: Mux Peer switch addr not yet configured, port 'Ethernet4'
65963:Feb 22 14:53:40.442960  WARNING swss#orchagent: :- addOperation: Mux entry for port 'Ethernet4' doesn't exist
65994:Feb 22 14:53:40.443560  NOTICE swss#orchagent: :- handleMuxCfg: Ethernet4: 192.168.0.3 was added to ignored neighbor list
65995:Feb 22 14:53:40.443579  INFO swss#orchagent: :- handleMuxCfg: Mux Peer switch addr not yet configured, port 'Ethernet4'
66025:Feb 22 14:53:40.445502  WARNING swss#orchagent: :- addOperation: Mux entry for port 'Ethernet4' doesn't exist
66056:Feb 22 14:53:40.446640  NOTICE swss#orchagent: :- handleMuxCfg: Ethernet4: 192.168.0.3 was added to ignored neighbor list
66057:Feb 22 14:53:40.446689  INFO swss#orchagent: :- handleMuxCfg: Mux Peer switch addr not yet configured, port 'Ethernet4'
66087:Feb 22 14:53:40.447315  WARNING swss#orchagent: :- addOperation: Mux entry for port 'Ethernet4' doesn't exist
66118:Feb 22 14:53:40.449097  NOTICE swss#orchagent: :- handleMuxCfg: Ethernet4: 192.168.0.3 was added to ignored neighbor list
66119:Feb 22 14:53:40.449158  INFO swss#orchagent: :- handleMuxCfg: Mux Peer switch addr not yet configured, port 'Ethernet4'
66149:Feb 22 14:53:40.450438  WARNING swss#orchagent: :- addOperation: Mux entry for port 'Ethernet4' doesn't exist
66180:Feb 22 14:53:40.451145  NOTICE swss#orchagent: :- handleMuxCfg: Ethernet4: 192.168.0.3 was added to ignored neighbor list
66181:Feb 22 14:53:40.451145  INFO swss#orchagent: :- handleMuxCfg: Mux Peer switch addr not yet configured, port 'Ethernet4'
66211:Feb 22 14:53:40.451844  WARNING swss#orchagent: :- addOperation: Mux entry for port 'Ethernet4' doesn't exist
66284:Feb 22 14:53:40.556712  NOTICE swss#orchagent: :- setHostIntfsStripTag: Set SAI_HOSTIF_VLAN_TAG_KEEP to host interface: Ethernet4
66285:Feb 22 14:53:40.556712  NOTICE swss#orchagent: :- addBridgePort: Add bridge port Ethernet4 to default 1Q bridge
66286:Feb 22 14:53:40.559869  NOTICE swss#orchagent: :- addVlanMember: Add member Ethernet4 to VLAN Vlan1000 vid:1000 pid1000000000003
66287:Feb 22 14:53:40.560985  NOTICE swss#orchagent: :- setPortPvid: Set pvid 1000 to port: Ethernet4
66338:Feb 22 14:53:40.674642  INFO swss#orchagent: :- addZeroMacTunnelRoute: Creating tunnel route for neighbor 192.168.0.3
67068:Feb 22 14:53:40.853685  INFO swss#orchagent: :- setObjectReference: Obj PORT_QOS_MAP.Ethernet4 Field dscp_to_tc_map: Add reference to DSCP_TO_TC_MAP AZURE (now 12)
67069:Feb 22 14:53:40.853787  INFO swss#orchagent: :- setObjectReference: Obj PORT_QOS_MAP.Ethernet4 Field pfc_to_queue_map: Add reference to MAP_PFC_PRIORITY_TO_QUEUE AZURE (now 12)
67070:Feb 22 14:53:40.853787  INFO swss#orchagent: :- setObjectReference: Obj PORT_QOS_MAP.Ethernet4 Field tc_to_pg_map: Add reference to TC_TO_PRIORITY_GROUP_MAP AZURE (now 12)
67071:Feb 22 14:53:40.853887  INFO swss#orchagent: :- setObjectReference: Obj PORT_QOS_MAP.Ethernet4 Field tc_to_queue_map: Add reference to TC_TO_QUEUE_MAP AZURE (now 12)
67072:Feb 22 14:53:40.855239  INFO swss#orchagent: :- handlePortQosMapTable: Applied AZURE to port Ethernet4
67073:Feb 22 14:53:40.860266  INFO swss#orchagent: message repeated 3 times: [ :- handlePortQosMapTable: Applied AZURE to port Ethernet4]
67074:Feb 22 14:53:40.860266  INFO swss#orchagent: :- handlePortQosMapTable: Applied PFC bits 0x18 to port Ethernet4
67269:Feb 22 14:53:41.080393  NOTICE swss#orchagent: :- handleMuxCfg: Ethernet4: 192.168.0.3 was added to ignored neighbor list
67270:Feb 22 14:53:41.080435  INFO swss#orchagent: :- handleMuxCfg: Mux Peer switch addr not yet configured, port 'Ethernet4'
67302:Feb 22 14:53:41.098164  NOTICE swss#orchagent: :- createBindAclTableGroup: Create ingress ACL table group and bind port Ethernet4 to it
67305:Feb 22 14:53:41.101874  WARNING write_standby: Applying state to interfaces {'Ethernet12': 'active', 'Ethernet16': 'active', 'Ethernet20': 'active', 'Ethernet24': 'active', 'Ethernet28': 'active', 'Ethernet32': 'active', 'Ethernet36': 'active', 'Ethernet4': 'active', 'Ethernet40': 'active', 'Ethernet44': 'active', 'Ethernet48': 'active', 'Ethernet52': 'standby', 'Ethernet56': 'standby', 'Ethernet60': 'standby', 'Ethernet64': 'standby', 'Ethernet68': 'standby', 'Ethernet72': 'standby', 'Ethernet76': 'standby', 'Ethernet8': 'active', 'Ethernet80': 'standby', 'Ethernet84': 'standby', 'Ethernet88': 'standby', 'Ethernet92': 'standby', 'Ethernet96': 'standby'}
67379:Feb 22 14:53:41.256472  WARNING swss#orchagent: :- addOperation: Mux entry for port 'Ethernet4' doesn't exist
67445:Feb 22 14:53:41.592281  INFO caclmgrd[134695]: dhcp packet mark update : '('Ethernet4', 'SET', (('mark', '0x67008'),))'
68665:Feb 22 14:53:44.563443  NOTICE swss#orchagent: :- handleMuxCfg: Ethernet4: 192.168.0.3 was added to ignored neighbor list
68666:Feb 22 14:53:44.563477  INFO swss#orchagent: :- stateStandby: Set state to Standby for Ethernet4
68667:Feb 22 14:53:44.563477  INFO swss#orchagent: :- aclHandler: Skip programming ACL for mux port Ethernet4, cable type 1, add 1
68668:Feb 22 14:53:44.563511  NOTICE swss#orchagent: :- handleMuxCfg: Mux entry for port 'Ethernet4' was added, cable type 1
68819:Feb 22 14:53:44.840178  INFO swss#neighsyncd: :- onMsg: Unable to resolve Vlan1000:192.168.0.3, setting zero MAC
68821:Feb 22 14:53:44.840998  INFO swss#orchagent: :- getState: Get state request for Ethernet4, state standby
68822:Feb 22 14:53:44.841193  NOTICE swss#orchagent: :- addOperation: Mux setting State DB entry (hw state unknown, mux state unknown) for port Ethernet4
68913:Feb 22 14:53:44.872133  NOTICE swss#orchagent: :- setState: [Ethernet4] Set MUX state from standby to active
68914:Feb 22 14:53:44.872308  INFO swss#orchagent: :- stateActive: Set state to Active for Ethernet4
68921:Feb 22 14:53:44.877403  INFO swss#orchagent: :- aclHandler: Skip programming ACL for mux port Ethernet4, cable type 1, add 0
68923:Feb 22 14:53:44.877403  NOTICE swss#orchagent: :- addOperation: Mux State set to active for port Ethernet4
69014:Feb 22 14:53:44.965084  INFO caclmgrd[134695]: mux cable update : '('Ethernet4', 'SET', (('state', 'unknown'),))'
69614:Feb 22 14:53:45.655126  INFO swss#orchagent: :- getState: Get state request for Ethernet4, state active
69615:Feb 22 14:53:45.655197  NOTICE swss#orchagent: :- addOperation: Mux setting State DB entry (hw state unknown, mux state unknown) for port Ethernet4
69628:Feb 22 14:53:45.669971  INFO caclmgrd[134695]: mux cable update : '('Ethernet4', 'SET', (('state', 'unknown'),))'
71875:Feb 22 14:53:47.948243  INFO swss#neighsyncd: :- onMsg: Unable to resolve Vlan1000:192.168.0.3, setting zero MAC
```

## analysis
From the syslog:
```
66338:Feb 22 14:53:40.674642 INFO swss#orchagent: :- addZeroMacTunnelRoute: Creating tunnel route for neighbor 192.168.0.3
...
67269:Feb 22 14:53:41.080393 NOTICE swss#orchagent: :- handleMuxCfg: Ethernet4: 192.168.0.3 was added to ignored neighbor list
67270:Feb 22 14:53:41.080435 INFO swss#orchagent: :- handleMuxCfg: Mux Peer switch addr not yet configured, port 'Ethernet4'
```
At the time `NeighOrch` calls `addZeroMacTunnelRoute` to let `muxorch` update zero mac neighbor, the `MuxCable` object for `Ethernet4` is not created yet, so the event is ignored:
https://github.com/sonic-net/sonic-swss/blob/f66abeda6a6e67b40b997b779ec3a6a362632fc1/orchagent/neighorch.cpp#L1758-L1765
https://github.com/sonic-net/sonic-swss/blob/f66abeda6a6e67b40b997b779ec3a6a362632fc1/orchagent/muxorch.cpp#L1100-L1105

But in `addZeroMacTunnelRoute`, `NeighOrch` caches this zero-mac neighbor, for any following zero-mac neighbor events, `NeighOrch` will believe that `MuxOrch` has already install the standalone tunnel route and ignore those events.
https://github.com/sonic-net/sonic-swss/blob/f66abeda6a6e67b40b997b779ec3a6a362632fc1/orchagent/neighorch.cpp#L742-L753

### PR DESCRIPTION
**Pull request by lolyu**
**What I did**
The issue is that `MuxOrch::m_syncdNeighbors` assumes all cached zero-mac neighbors have tunnel routes installed. The check before adding tunnel routes ignores the following zero-mac neighbor events.
Let's ensure that, if a zero-mac neighbor is present in `MuxOrch::m_syncdNeighbors`, it has a tunnel route installed.
So let's check the tunnel route install success before adding a neighbor to `MuxOrch::m_syncdNeighbors`.

**Why I did it**
To fix #2675
If `MuxOrch` is not fully initialized, and there is a `FAILED` neighbor added to kernel, the tunnel route creation will fail. But the subsequent `FAILED` neighbor events cannot trigger tunnel route creation because `MuxOrch::m_syncdNeighbors` caches the first event and regard the tunnel as already installed.

**How I verified it**
UT and verify on testbed.

**Details if related**

### CODE REVIEW

File: orchagent/neighorch.cpp [hunk 1]
```diff
@@ -1755,12 +1759,18 @@ void NeighOrch::updateSrv6Nexthop(const NextHopKey &nh, const sai_object_id_t &n
...
+
+bool NeighOrch::addZeroMacTunnelRoute(const NeighborEntry& entry, const MacAddress& mac)
 {
     SWSS_LOG_INFO("Creating tunnel route for neighbor %s", entry.ip_address.to_string().c_str());
     MuxOrch* mux_orch = gDirectory.get<MuxOrch*>();
     NeighborUpdate update = {entry, mac, true};
     mux_orch->update(SUBJECT_TYPE_NEIGH_CHANGE, static_cast<void *>(&update));
-    m_syncdNeighbors[entry] = { mac, false };
-}
+    if (mux_orch->isStandaloneTunnelRouteInstalled(entry.ip_address))
```
Comment (yxieca) [inline orchagent/neighorch.cpp:1769]: Shouldn't this check be moved to the beginning of the function? What would happen when calling mux_orch->update() when the tunnel routes is already installed?

Comment (Ndancejic) [reply orchagent/neighorch.cpp:1769]: There's a check in the mux_orch->update() path that checks for this so it should be safe
```
if (update.add)
{
    if (standalone_tunnel_neigh_it == standalone_tunnel_neighbors_.end())
    {
        createStandaloneTunnelRoute(update.entry.ip_address);
    }
    /* If the MAC address in the neighbor entry is zero but the neighbor IP
     * is already present in standalone_tunnel_neighbors_, assume we have already
     * added a tunnel route for it and exit early
     */
    return;
}
```

**Review by Ndancejic — APPROVED** [review]
LGTM

File: orchagent/neighorch.cpp (hunk 1 above)
Comment (zjswhhh) [reply orchagent/neighorch.cpp:1769]: The check should be at the end. Imagine the tunnel route is first added.

**Review by theasianpianist — DISMISSED** [review]
lgtm!

File: tests/test_mux.py [hunk 2]
```diff
@@ -1226,6 +1226,35 @@ def test_neighbor_miss(
...
+        test_ip = self.SERV1_SOC_IPV4
+        self.ping_ip(dvs, test_ip)
+
+        # no mux present, no standalone tunnel route installed
+        self.check_neighbor_state(dvs, dvs_route, test_ip, expect_route=False)
+
+        # setup the mux
+        config_db = dvs.get_config_db()
+        self.create_mux_cable(config_db)
+
```
Comment (zjswhhh) [inline tests/test_mux.py:1245]: Should we add another `ping_ip` and `check_neighbor_state` *after* mux is setup && *before* set port state to standby?

**Review by zjswhhh — DISMISSED** [review]
Changes look good to me. 

Unit test can be improved a bit, but not mandatory.

File: tests/test_mux.py (hunk 2 above)
Comment (lolyu) [reply tests/test_mux.py:1251]: good point, updated.

**Review by theasianpianist — APPROVED** [review]

**Review by Ndancejic — APPROVED** [review]

**Review by zjswhhh — APPROVED** [review]

**Comment by yxieca** [comment]
Latest test passed. However pipelien failed to update the results to PR and also rejectign retest request. Force merge this PR.

**Comment by lolyu** [comment]
> @lolyu could you raise PR for 202211?

@StormLiangMS PR to 202211 ready: https://github.com/sonic-net/sonic-swss/pull/2696
